metanorma/mnconvert

src/main/java/org/metanorma/MN2STS_XsltConverter.java
src/main/java/org/metanorma/STS2MN_XsltConverter.java
src/main/java/org/metanorma/XsltConverter.java
src/main/java/org/metanorma/mnconvert.java

I did some improvement during debugging mnconvert to understand a bit how it works
@Intelligent2013 up to you to decide about merge

Add commont XstlConverter interface

---

.github/workflows/release.yml

metanorma/mnconvert-ruby#1 enable repository_dispatch to mnconvert-ruby

---

doc/mn-xml-mapping.adoc

As requested in https://github.com/metanorma/metanorma.org/issues/464.

Add MN XML mapping to ISOSTS and NISO STS (adoc)

---

.github/workflows/test.yml
Makefile

workflow updated for testing

---

src/main/resources/mn2ieee.xsl
src/main/resources/mn2xml.xsl
src/main/resources/sts2mn.adoc.xsl

Ieee update

---

README.adoc
pom.xml
src/main/resources/mn2ieee.xsl
src/main/resources/mn2xml.xsl
src/main/resources/sts2mn.adoc.xsl

Mixed citation

---

README.adoc
pom.xml
src/main/java/org/metanorma/MN2STS_XsltConverter.java

validation skipped added, #195

---

src/main/resources/mn2xml.xsl

mn2xml.xslt updated for uri and ext-link processing, #239

---

src/main/resources/mn2xml.xsl

mn2xml.xslt updated for ISO std-meta generation, #198

---

src/main/resources/mn2xml.xsl

mn2xml.xsl updated for permissions, #199

---

src/main/resources/mn2sts.xsl
src/main/resources/mn2xml.xsl

mn2xml.xsl updated for amendment issues fixing, #253

---

src/main/resources/mn2xml.xsl

mn2xml.xsl updated for amendment empty label, #202

---

src/main/resources/mn2xml.xsl

mn2xml.xsl updated for annex content-type, #205

---

src/main/resources/mn2sts.xsl

mn2xml.xsl updated for bibitem id, #206

---

src/main/resources/mn2xml.xsl
src/main/resources/sts2mn.adoc.xsl

mn2xml.xsl updated for Warning, Important and Caution notes, #213

---

src/main/resources/mn2xml.xsl

mn2xml.xsl updated for abbreviations, #238

---

src/main/resources/sts2mn.adoc.xsl
src/main/resources/sts2mn.xsl

sts2mn xsl updated for partOfSpeech processing, #229

---

src/main/resources/mn2sts.xsl
src/main/resources/sts2mn.adoc.xsl
src/main/resources/sts2mn.xsl

xsl updated for termType processing, #230

---

src/main/resources/mn2sts.xsl
src/main/resources/mn2xml.xsl

mn2sts xml updated for xref ref-type processing, #236

---

src/main/resources/mn2sts.xsl

mn2sts xml updated for fn style, #237

---

src/main/resources/mn2xml.xsl

mn2xml.xsl updated for figure key table, list, #227

---

src/main/resources/mn2sts.xsl

mn2xml.xsl updated for table footnote ref-type, #223

---

src/main/resources/mn2xml.xsl

mn2xml.xsl updated bolded text in ISO table header cells , #221

---

src/main/resources/mn2xml.xsl

mn2xml.xsl updated for IEC, table width attribute removed, #220

---

src/main/resources/mn2xml.xsl

mn2xml.xsl updated for editing-instruction processing, #219

---

src/main/resources/mn2xml.xsl
src/main/resources/sts2mn.adoc.xsl
src/main/resources/sts2mn.xsl

xslt updated for supplementary material link processing, #241

---

src/main/resources/mn2sts.xsl
src/main/resources/sts2mn.adoc.xsl
src/main/resources/sts2mn.xsl

xslt updated for cross-references to terms external processing, #231

---

src/main/resources/mn2xml.xsl
src/main/resources/sts2mn.adoc.xsl
src/main/resources/sts2mn.common.xsl
src/main/resources/sts2mn.xsl

xslt updated for additions and deletions markup processing, #212

---

.github/workflows/test.yml

Change caching to ensure that correct version of bundler is used

---

src/main/resources/mn2xml.xsl

mn2xml.xsl update for Latex support, #277

---

src/main/resources/mn2xml.xsl

mn2xml updated for empty tables, #299

---

.github/workflows/test.yml

Pngcheck fix

---

README.adoc
pom.xml
src/main/resources/mn2sts.xsl

mn2sts.xsl updated for entailedTerm issue fix, #244

---

src/main/resources/mn2xml.xsl

mn2xml.xsl updated for reference to term, #308

---

src/main/resources/mn2xml.xsl

mn2xml.xsl updated for reference to bibliographic item, #311

---

src/main/resources/mn2ieee.xsl
src/main/resources/mn2xml.xsl
src/main/resources/sts2mn.xsl

xslt updated, misc-container replaced with metanorma-extension, #319

---

src/main/resources/mn2sts.xsl
src/main/resources/mn2xml.xsl

mn2xml.xsl updated for front clauses sec-type, #325

---

.github/workflows/prepare.yml
.github/workflows/release.yml
.github/workflows/test.yml
Makefile
src/test/java/org/metanorma/mn2ieeeTests.java
src/test/resources/ieee/ieee.test.xml

updated for IEEE DTD test, #330

---

src/main/resources/mn2sts.xsl
src/main/resources/mn2xml.xsl

mn2sts.xsl updated for index, #327

---

Makefile
src/main/resources/sts2mn.adoc.xsl
src/main/resources/sts2mn.common.xsl

Pas update

---

src/main/resources/sts2mn.adoc.xsl

Adoc update

---

README.adoc
pom.xml
src/main/resources/mn2xml.xsl

mn2xsl.xsl updated for bsi flex errors, #345

---

src/main/resources/mn2xml.xsl

mn2xml.xsl update for fix validation error, metanorma/metanorma-bsi#179

---

README.adoc
pom.xml
src/main/resources/sts2mn.adoc.xsl

Xslt update

---

src/main/resources/sts2mn.adoc.xsl

sts2mn.adoc.xsl updated for [digits] references, #362

---

README.adoc
pom.xml
src/main/resources/mn2xml.xsl
src/main/resources/sts2mn.adoc.xsl
src/main/resources/sts2mn.common.xsl

Update for doi

---

README.adoc
pom.xml
src/main/resources/mn2xml.xsl

Update PAS colors

---

README.adoc
pom.xml
src/main/resources/sts2mn.adoc.xsl

xref subfigure

---

README.adoc
pom.xml
src/main/resources/mn2xml.xsl

mn2xml.xsl updated for metanorma/iso-10303-2#279

---

src/main/resources/mn2xml.xsl

mn2xml.xsl updated for preformat code, #218

---

README.adoc
src/main/resources/mn2sts.xsl
src/main/resources/mn2xml.xsl

mn2sts xslt updated for metanorma/metanorma-iso#648 and #398

---

README.adoc
pom.xml
src/main/resources/mn2xml.xsl

Conversion issue fix

---

README.adoc
pom.xml
src/main/resources/mn2sts.xsl

fix spaces the target attribute, metanorma/iso-19135#37

---

README.adoc
pom.xml
src/main/resources/mn2sts.xsl
src/main/resources/mn2xml.xsl
src/main/resources/sts2mn.adoc.xsl

updated for letter-symbol support, #230

---

.github/workflows/release.yml
.github/workflows/test.yml
README.adoc
pom.xml
src/main/resources/mn2xml.xsl

fixing issue #410

---

README.adoc
pom.xml
src/main/resources/mn2xml.xsl

mn2xml.xsl updated for metanorma/metanorma-bsi#508

---

README.adoc
pom.xml
src/main/resources/mn2xml.xsl

Update for new Presentation XML

---

README.adoc
pom.xml
src/main/resources/mn2xml.xsl

mn2xml xslt updated to fix validation issue, #418

---

README.adoc
pom.xml
src/main/resources/mn2xml.xsl

mn2xml.xsl updated for new term tags, #418

---

.github/workflows/release.yml
.github/workflows/test.yml
Makefile
README.adoc
pom.xml
src/main/resources/mn2ieee.xsl
src/main/resources/mn2sts.xsl
src/main/resources/mn2xml.remove_namespace.xsl
src/main/resources/mn2xml.xsl
src/test/resources/rice-en.cd.xml

Update pres xml

---

README.adoc
pom.xml
src/main/resources/mn2sts.xsl
src/main/resources/mn2xml.remove_namespace.xsl
src/main/resources/mn2xml.xsl

missing eref fixing, metanorma/iso-10303#613

---

src/main/resources/mn2xml.xsl

mn2xml.xsl updated to ignore metanorma-extension/toc

---

README.adoc
pom.xml
src/main/resources/mn2ieee.xsl
src/test/resources/ieee/ieee.test.xml

mn2ieee.xsl updated for new editorialgroup format, #438
